### ISSUE TITLE
bug when first-day-of-week starts by "1"

### ISSUE THREAD

**Issue by nokauttorton** [jiayingy/vue-single-date-picker#24]
<img width="315" alt="Снимок экрана 2021-03-19 в 19 05 00" src="https://user-images.githubusercontent.com/34866756/111809433-07398d80-88e6-11eb-892d-4c604e5af634.png">

Hi, when i initialised component with first-day-of-week by "1" in last week are doubling days(

<img width="579" alt="Снимок экрана 2021-03-19 в 19 12 05" src="https://user-images.githubusercontent.com/34866756/111810406-06edc200-88e7-11eb-950c-79a876499c21.png">

**Comment by jiayingy** [comment]
Fixed at #25
